In [ ]:
import pandas as pd
import numpy as np
from numpy import random

In [ ]:

r1=[random.randint(100) for _ in range(4)]
r2=[random.randint(100) for _ in range(4)]
r3=[random.randint(100) for _ in range(4)]
r4=[random.randint(100) for _ in range(4)]
df = pd.DataFrame([r1,r2,r3,r4])
print(df)

    0   1   2   3
0  61  52  50  53
1  95  31  29  54
2  40  94  55  54
3  78  62  85  58

In [ ]:
df.columns=['Random Value 1','Random Value 2','Random Value 3','Random Value 4']
df

   Random Value 1  Random Value 2  Random Value 3  Random Value 4
0              61              52              50              53
1              95              31              29              54
2              40              94              55              54
3              78              62              85              58

In [ ]:
df.describe()

       Random Value 1  Random Value 2  Random Value 3  Random Value 4
count        4.000000        4.000000        4.000000        4.000000
mean        68.500000       59.750000       54.750000       54.750000
std         23.530123       26.234519       23.099423        2.217356
min         40.000000       31.000000       29.000000       53.000000
25%         55.750000       46.750000       44.750000       53.750000
50%         69.500000       57.000000       52.500000       54.000000
75%         82.250000       70.000000       62.500000       55.000000
max         95.000000       94.000000       85.000000       58.000000

In [ ]:
df.isnull().any()

Random Value 1    False
Random Value 2    False
Random Value 3    False
Random Value 4    False
dtype: bool

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Random Value 1  4 non-null      int64
 1   Random Value 2  4 non-null      int64
 2   Random Value 3  4 non-null      int64
 3   Random Value 4  4 non-null      int64
dtypes: int64(4)
memory usage: 256.0 bytes

In [ ]:
df.loc[:,'Random Value 2':'Random Value 3']

   Random Value 2  Random Value 3
0              52              50
1              31              29
2              94              55
3              62              85

In [ ]:
df.iloc[:,1:3]

   Random Value 2  Random Value 3
0              52              50
1              31              29
2              94              55
3              62              85